name             'elklogging'
maintainer       'Nick Ramirez'
maintainer_email 'nickram44@gmail.com'
license          'all_rights'
description      'Installs and configures logstash as a service, elasticsearch, kibana and redis'
long_description 'Installs/Configures elklogging'
version          '0.3.15'

depends 'apt'
depends 'java'